version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.11

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: make prereq
      - run: make ci
      - run: make build

  release:
    executor: golang
    steps:
      - checkout
      - run: make prereq
      - run: make cross-compile

workflows:
  version: 2
  netgear_cm_exporter:
    jobs:
    - build
    - release

